# Generated by Django 5.0.6 on 2024-05-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao_longa', models.TextField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('numero_de_pecas', models.IntegerField(default=0)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('cotacao_efetivada', models.BooleanField(default=False)),
                ('data_efetivacao', models.DateField(blank=True, null=True)),
                ('codigo_fusofix', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
