# Generated by Django 5.0.6 on 2024-05-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cotacao_efetivada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_efetivacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_efetivacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
