# Generated by Django 5.0.6 on 2024-05-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_cotacao_efetivada_produto_data_efetivacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
