# Generated by Django 5.0.6 on 2024-05-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_fusofix',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
